static const char* const languageStrings[][2] = {
{"Settings","设置"},
{"Appearance","外观"},
{"Light","浅色"},
{"Dark","深色"},

{"Display","显示"},
{"Sound","声音"},
{"Interface","界面"},
{"System","系统"},

{"Scaling","画面缩放"},
{"Filtering","滤波"},
{"Sharp","清晰"},
{"Smooth","平滑"},
{"Frame skip","跳帧"},
{"Volume","音量"},
{"Show FPS","显示帧率"},
{"Language","语言"},
{"System info","系统信息"},
{"Open","打开"},
{"On","开"},
{"Off","关"},
{"ORIGINAL","原尺寸"},
{"FIT","保持比例"},
{"FULL","铺满屏幕"},
{"AUTO","自动"},
{"ONE","隔帧"},
{"OFF","关闭"},
{"Resume","继续"},
{"Cheats","金手指"},
{"Screenshots","查看截图"},
{"Return to menu","返回菜单"},
{"Paused","游戏暂停"},
{"No cheat rules","没有可用规则"},
{"Saved","设置已保存"},
{"Cannot save cheat settings","无法保存金手指设置"},
{"Screenshot saved","截图已保存"},
{"Screenshot failed: check free space","截图失败，请检查存储空间"},
{"Cannot read screenshot. Try another.","截图无法读取，可翻页查看其他截图"},
{"Device","设备"},
{"Firmware","系统版本"},
{"CPU clock","CPU 频率"},
{"CPU usage","CPU 占用"},
{"Sampling","正在采样"},
{"Unavailable","无法获取"},
{"Heap used/reserved","堆已用 / 已保留"},
{"Heap/system free","堆空闲 / 系统剩余"},
{"Storage used/total","存储已用 / 总量"},
{"Storage free","存储剩余"},
{"Page CPU usage; memory excludes VRAM","CPU 为此页面的实时占用；内存统计不含显存"},
{"No game files","没有找到游戏"},
{"Load failed - see log","载入失败，请查看日志"},
{"Games","游戏"},
{"Scanning","正在扫描"},
{"No .cheats file for this game","未找到本游戏的 .cheats 文件"},
{"Invalid cheats; previous rules kept","金手指格式错误，原规则保留"},
{"Loading","正在加载"},
{"Opening game","打开游戏"},
{"Reading file","读取文件"},
{"Parsing game","解析游戏数据"},
{"Preparing scene","准备场景"},
{"Opening video","打开视频"},
{"Indexing video","分析视频数据"},
{"Separating streams","分离音视频"},
{"Preparing video","准备视频解码"},
{"Theme color","主题颜色"},
{"Cyan","青色"},
{"Blue","蓝色"},
{"Purple","紫色"},
{"Orange","橙色"},
{"Green","绿色"},
{"Change","修改"},
{"Back","返回"},
{"Confirm","确认"},
{"Toggle","开关"},
{"Reload","重载"},
{"No screenshots","暂无截图"},
{"Capture","截图"},
{"Browse","翻页"},
{"Info","信息"},
{"Resample","重新采样"},
{"Play","开始"},
{"Menu","菜单"},
{"Exit","退出"},
{"Delete","删除"},
{"Cancel","取消"},
{"Delete this screenshot?","删除这张截图？"},
{"Cannot delete screenshot","删除失败，请检查存储卡"},
{"About","关于"},
{"Author","作者"},
{"Acknowledgements","致谢"},
};
